---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of API
components:
  schemas:
    district_with_polygon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
    district:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
    area_with_polygon:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        emblem_url:
          type: string
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - polygon
      - polygon_type
      - center_coord
    area:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        emblem_url:
          type: string
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
paths:
  "/areas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Show area by id
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 1
                    population: 617896
                    square: 52191.78
                    name: Dorine Garden
                    population_density: 34.64
                    square_housing_stock: 84.86
                    living_square_per_person: 90.27
                    district_id: 1
                    2gis_id: 8444642792
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--92836fbc23990e7111fe308ab6f8cf1903dc4f96/emblem.png
                    polygon:
                    - - - 25778.716485
                        - 76700.375921
                      - - 70902.092687
                        - 43498.493228
                    polygon_type: 1
                    center_coord:
                    - 14194.092086
                    - 65665.927568
              schema:
                "$ref": "#/components/schemas/area_with_polygon"
        '404':
          description: Not found
  "/districts/{district_id}/areas":
    parameters:
    - name: district_id
      in: path
      description: district_id
      required: true
      schema:
        type: string
    get:
      summary: Array areas by district
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 4
                    population: 840817
                    square: 94313.69
                    name: Huels Points
                    population_density: 87.27
                    square_housing_stock: 27.14
                    living_square_per_person: 25.59
                    district_id: 4
                    2gis_id: 1476753949
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26cdb2240b64ed4bc6a8b34c259fbee6142897ae/emblem.png
                  - id: 5
                    population: 540927
                    square: 96958.85
                    name: Oscar Circles
                    population_density: 92.76
                    square_housing_stock: 23.14
                    living_square_per_person: 42.93
                    district_id: 4
                    2gis_id: 3773505410
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--76aba94711d43b8186be73df811f19fc35e40aae/emblem.png
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/area"
  "/districts":
    get:
      summary: Array districts
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 5
                    name: Runte Track
                    short_name: MO
                    square: 23.14
                    population: 667121
                    2gis_id: 4080024936
                  - id: 6
                    name: Sanford Row
                    short_name: IL
                    square: 44.46
                    population: 595172
                    2gis_id: 5970796376
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/district"
  "/districts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Show district by id
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 7
                    name: Jerome Manors
                    short_name: CA
                    square: 63.76
                    population: 194535
                    2gis_id: 4009662230
                    polygon:
                    - - - 39411.573934
                        - 69696.311539
                      - - 67415.564999
                        - 78147.723606
                    polygon_type: 0
                    center_coord:
                    - 47779.103706
                    - 35310.498521
              schema:
                "$ref": "#/components/schemas/district_with_polygon"
        '404':
          description: Not found
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: 188.72.109.162:3000
